name: "ltp"

on:
  push:
    branches:
      - 'release-**'
    paths-ignore:
      - 'docs/**'
  pull_request:
    #The branches below must be a subset of the branches above
    branches:
      - 'main'
    paths-ignore:
      - 'docs/**'

jobs:
  ltpfsmanyclient:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.x'

      - name: Set up Docker
        uses: docker-practice/actions-setup-docker@master

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Build linux target
        run: |
          make juicefs
          cp .github/workflows/bash/rm_fs /tmp/
          cp .github/workflows/bash/rm_list.sh /tmp/

      - name: Run Redis
        run: |
          sudo docker run -d --name redis -v redis-data:/data  \
          -p 6379:6379  redis redis-server --appendonly yes

      - name: Juicefs Format
        run: |
          sudo ./juicefs format redis://127.0.0.1:6379/1 pics

      - name: Juicefs Mount
        run: |
          sudo ./juicefs mount -d redis://127.0.0.1:6379/1 /tmp/jfs --no-usage-report &
          sudo ./juicefs mount -d redis://127.0.0.1:6379/1 /juice/data1 --no-usage-report &
          sudo ./juicefs mount -d redis://127.0.0.1:6379/1 /juice/data2 --no-usage-report &
          sleep 5s
          stat /tmp/jfs
          stat /juice/data1
          stat /juice/data2

      - name: LTP FS
        run: |
          git clone https://github.com/linux-test-project/ltp.git
          cd ltp
          make autotools
          ./configure
          make
          sudo make install
          cd /opt/ltp
          sudo chmod +x /tmp/rm_list.sh
          sudo chmod 777 runtest/fs
          sudo /tmp/rm_list.sh /tmp/rm_fs /opt/ltp/runtest/fs
          sudo ./runltp -d /juice/data1 -f fs_bind,fs_perms_simple,fsx,io,smoketest -C result_other_data1.log.failed -T result_other_data1.log.tconf -l result_other_data1.log &
          sudo ./runltp -d /juice/data2 -f fs_bind,fs_perms_simple,fsx,io,smoketest -C result_other_data2.log.failed -T result_other_data2.log.tconf -l result_other_data2.log &
          sudo ./runltp -d /tmp/jfs -f fs_bind,fs_perms_simple,fsx,io,smoketest -C result_other_tmp.log.failed -T result_other_tmp.log.tconf -l result_other_tmp.log | tee /tmp/result_other_tmp
          echo "check other result begin"
          if [ -f "/opt/ltp/results/result_other_data1.log.failed" ];then cat /opt/ltp/results/result_other_data1.log.failed;exit 1; fi
          if [ -f "/opt/ltp/results/result_other_data2.log.failed" ];then cat /opt/ltp/results/result_other_data2.log.failed;exit 1; fi
          if [ -f "/opt/ltp/results/result_other_tmp.log.failed" ];then cat /opt/ltp/results/result_other_tmp.log.failed;exit 1; fi
          echo "check other result end"
          sudo ./runltp -d /juice/data1 -f fs -C result_data1.log.failed -T result_data1.log.tconf -l result_data1.log
          sleep 60s
          sudo ./runltp -d /juice/data2 -f fs -C result_data2.log.failed -T result_data2.log.tconf -l result_data2.log
          sleep 60s
          sudo ./runltp -d /tmp/jfs -f fs -C result_tmp.log.failed -T result_tmp.log.tconf -l result_tmp.log | tee /tmp/result_tmp
          echo "check fs result begin"
          if [ -f "/opt/ltp/results/result_data1.log.failed" ];then cat /opt/ltp/results/result_data1.log.failed;exit 1; fi
          if [ -f "/opt/ltp/results/result_data2.log.failed" ];then cat /opt/ltp/results/result_data2.log.failed;exit 1; fi
          if [ -f "/opt/ltp/results/result_tmp.log.failed" ];then cat /opt/ltp/results/result_tmp.log.failed;exit 1; fi
          echo "check fs result end"


      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3