name: "pjdfstest"

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
  pull_request:
    #The branches below must be a subset of the branches above
    branches:
      - 'main'
    paths-ignore:
      - 'docs/**'

jobs:
  pjdfsmanyclient:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.x'

      - name: Set up Docker
        uses: docker-practice/actions-setup-docker@master

      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5.34'

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Build linux target
        run: make juicefs

      - name: Run Redis
        run: |
          sudo docker run -d --name redis -v redis-data:/data  \
          -p 6379:6379  redis redis-server --appendonly yes

      - name: Juicefs Format
        run: |
          sudo ./juicefs format redis://127.0.0.1:6379/1 --trash-days 0 pics

      - name: Juicefs Mount
        run: |
          sudo ./juicefs mount -d redis://127.0.0.1:6379/1 /tmp/jfs --no-usage-report &
          sudo ./juicefs mount -d redis://127.0.0.1:6379/1 /juice/data1 --no-usage-report &
          sudo ./juicefs mount -d redis://127.0.0.1:6379/1 /juice/data2 --no-usage-report &
          sleep 5s
          stat /tmp/jfs
          stat /juice/data1
          stat /juice/data2

      - name: Pjdfstest
        run: |
          sudo apt-get update
          sudo apt-get install -y libtap-harness-archive-perl
          cd /tmp/jfs/
          git clone https://github.com/pjd/pjdfstest.git
          cd pjdfstest
          autoreconf -ifs
          ./configure
          make pjdfstest
          cd /juice/data1/pjdfstest
          sudo prove -rv tests/ >/tmp/data1_result_tmp &
          sleep 60s
          cd /juice/data2/pjdfstest
          sudo prove -rv tests/ >/tmp/data2_result_tmp &
          sleep 60s
          cd /tmp/jfs/pjdfstest
          sudo prove -rv tests/ | tee /tmp/jfs_result_tmp
          head -n -2 /tmp/data1_result_tmp >/tmp/data1_result
          head -n -2 /tmp/data2_result_tmp >/tmp/data2_result
          head -n -2 /tmp/jfs_result_tmp >/tmp/jfs_result
          echo "check result begin"
          tail -n 1 /tmp/jfs_result_tmp
          tail_result= tail -n 1 /tmp/jfs_result_tmp | grep PASS
          echo "tail_result is "
          echo $tail_result
          if [[ $tail_result = "" ]]; then exit 1; fi
          echo "check result end"
          echo "diff begin"
          diff_jfs_data1=$(diff /tmp/jfs_result /tmp/data1_result)
          diff_jfs_data2=$(diff /tmp/jfs_result /tmp/data2_result)
          echo $diff_jfs_data1
          echo $diff_jfs_data2
          echo "diff end"
          if [[ $diff_jfs_data1 != "" ]] || [[ $diff_jfs_data2 != "" ]]; then exit 1; fi


      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3