name: "pjdfstest"

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
  pull_request:
    #The branches below must be a subset of the branches above
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: echo "::set-output name=test::hello"
      - id: step2
        run: echo "::set-output name=test::world"
      - name: Get IP
        run: |
          hostname -I
          sudo apt update
          sudo apt install redis-server
          sudo iptables -I INPUT -i ech0 -p icmp -s 0/0 -d 0/0 -j ACCEPT
          sudo ufw allow 6379
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}
      - name: Install Redis
        run: |
          hostname -I
          sudo apt update
          sudo apt install redis-server
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3