name: verify

on:
  push:
    branches:
    - release**
    paths:
    - '**.go'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code
      uses: actions/checkout@v1

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install g++-multilib

    - name: Build linux target
      run: |
        export GOPATH=$HOME/go
        make

    - name: Set up meta for fstests
      run: sudo make -C fstests setup
